import { defineConfig } from 'tsup'

export default defineConfig([
  {
    entry: ['src/index.ts'],
    format: ['esm'],
    dts: true,
    tsconfig: 'tsconfig.tsup.json',
    clean: false,
    sourcemap: true,
    splitting: false,
    treeshake: true,
    target: 'es2022',
    outDir: 'dist/esm',
    external: [
      'react',
      'react-dom',
      'zod',
      '@wildo-ai/custom-frontend-common-lib',
      '@wildo-ai/custom-shared-lib',
      '@wildo-ai/saas-frontend-lib',
      '@wildo-ai/saas-models',
      '@wildo-ai/presets-components-models',
      '@wildo-ai/presets-components',
      '@wildo-ai/zod-decorators',
    ],
  },
  {
    entry: ['src/index.ts'],
    format: ['cjs'],
    dts: false,
    tsconfig: 'tsconfig.tsup.json',
    clean: false,
    sourcemap: true,
    splitting: false,
    treeshake: true,
    target: 'es2022',
    outDir: 'dist/cjs',
    outExtension: () => ({ js: '.js' }),
    external: [
      'react',
      'react-dom',
      'zod',
      '@wildo-ai/custom-frontend-common-lib',
      '@wildo-ai/custom-shared-lib',
      '@wildo-ai/saas-frontend-lib',
      '@wildo-ai/saas-models',
      '@wildo-ai/presets-components-models',
      '@wildo-ai/presets-components',
      '@wildo-ai/zod-decorators',
    ],
  },
])

